/**
 * @file constants
 * @author cxtom(cxtom2008@gmail.com)
 */

/*
  Self-enclosing tags (stolen from node-htmlparser)
*/
export const singleTag = {
    area: true,
    base: true,
    basefont: true,
    br: true,
    col: true,
    command: true,
    embed: true,
    frame: true,
    hr: true,
    img: true,
    input: true,
    isindex: true,
    keygen: true,
    link: true,
    meta: true,
    param: true,
    source: true,
    track: true,
    wbr: true,
};

export const booleanAttr = {
    allowfullscreen: true,
    async: true,
    autofocus: true,
    autoplay: true,
    checked: true,
    compact: true,
    controls: true,
    declare: true,
    default: true,
    defaultchecked: true,
    defaultmuted: true,
    defaultselected: true,
    defer: true,
    disabled: true,
    enabled: true,
    formnovalidate: true,
    hidden: true,
    indeterminate: true,
    inert: true,
    ismap: true,
    itemscope: true,
    loop: true,
    multiple: true,
    muted: true,
    nohref: true,
    noresize: true,
    noshade: true,
    novalidate: true,
    nowrap: true,
    open: true,
    pauseonexit: true,
    readonly: true,
    required: true,
    reversed: true,
    scoped: true,
    seamless: true,
    selected: true,
    sortable: true,
    translate: true,
    truespeed: true,
    typemustmatch: true,
    visible: true,
};


export const noValueAttr = {
    's-else': true,
};


export const htmlTag = {
    html: true,
    body: true,
    base: true,
    head: true,
    link: true,
    meta: true,
    style: true,
    title: true,
    address: true,
    article: true,
    aside: true,
    footer: true,
    header: true,
    h1: true,
    h2: true,
    h3: true,
    h4: true,
    h5: true,
    h6: true,
    hgroup: true,
    nav: true,
    section: true,
    div: true,
    dd: true,
    dl: true,
    dt: true,
    figcaption: true,
    figure: true,
    hr: true,
    img: true,
    li: true,
    main: true,
    ol: true,
    p: true,
    pre: true,
    ul: true,
    a: true,
    b: true,
    abbr: true,
    bdi: true,
    bdo: true,
    br: true,
    cite: true,
    code: true,
    data: true,
    dfn: true,
    em: true,
    i: true,
    kbd: true,
    mark: true,
    q: true,
    rp: true,
    rt: true,
    rtc: true,
    ruby: true,
    s: true,
    samp: true,
    small: true,
    span: true,
    strong: true,
    sub: true,
    sup: true,
    time: true,
    u: true,
    var: true,
    wbr: true,
    area: true,
    audio: true,
    map: true,
    track: true,
    video: true,
    embed: true,
    object: true,
    param: true,
    source: true,
    canvas: true,
    script: true,
    noscript: true,
    del: true,
    ins: true,
    caption: true,
    col: true,
    colgroup: true,
    table: true,
    thead: true,
    tbody: true,
    td: true,
    th: true,
    tr: true,
    button: true,
    datalist: true,
    fieldset: true,
    form: true,
    input: true,
    label: true,
    legend: true,
    meter: true,
    optgroup: true,
    option: true,
    output: true,
    progress: true,
    select: true,
    textarea: true,
    details: true,
    dialog: true,
    menu: true,
    menuitem: true,
    summary: true,
    content: true,
    element: true,
    shadow: true,
    template: true,
};
